

## 1. gather操作

gather的pytorch官方文档是这样写的：

<img src="gather_官方文档.PNG"  width="800" height="1200" align="left" />


### 理解gather操作

`tensor_A.gather(dim, index)`: 按照 index 和指定的dim，取出tensor_A中的值；

(1) index和源tensor_A维度一致;

(3) 注意如何根据index选取tensor_A中的值： 

对于2-D tensor:

    if dim=0, output[i][j] = tensor_A[index[i][j]][j];
    
    if dim=1, output[i][j] = tensor_A[i][index[i][j]];

### 举例

In [1]:
import torch

tensor_A = 10 * torch.randn(3, 5)

In [2]:
tensor_A

tensor([[  2.8331, -12.4045, -21.8001,  -2.0757,   2.1819],
        [ -4.8956,   6.3741,   7.7292,  -2.6811,  13.2136],
        [ -5.2171, -16.6636, -11.2940,  -7.7390,  16.0390]])

In [3]:
index = [
    [0, 1, 2, 0, 0], 
    [2, 0, 0, 1, 2],
]
index = torch.tensor(index, dtype=torch.long)
print(index)
print(index.shape)

tensor([[0, 1, 2, 0, 0],
        [2, 0, 0, 1, 2]])
torch.Size([2, 5])


In [4]:
# dim = 0
tensor_C = tensor_A.gather(0, index)
tensor_C

tensor([[  2.8331,   6.3741, -11.2940,  -2.0757,   2.1819],
        [ -5.2171, -12.4045, -21.8001,  -2.6811,  16.0390]])


i=1, j=3; 

    tensor_A[index[i][j]][j] = tensor_A[1][3] = -2.6811
    
    output[i][j] = output[1][3] = -2.6811



In [6]:
# dim = 1
tensor_D = tensor_A.gather(1, index)
tensor_D

tensor([[  2.8331, -12.4045, -21.8001,   2.8331,   2.8331],
        [  7.7292,  -4.8956,  -4.8956,   6.3741,   7.7292]])

i=1, j=3; 

    tensor_A[i][index[i][j]] = tensor_A[1][1] = 6.3741
    
    output[i][j] = output[1][3] = 6.3741


